### ISSUE TITLE
Cannot convert Boolean object to Primitive value

### ISSUE THREAD

**Issue by upahsan** [java2script/java2script#19]
This issue is present in 2.0.0 but not 3.1.1

When trying to print a Boolean object, the javascript created by j2s crashes because it cannot convert the object to a primitive value.

Code:

    package test;
    
    public class BooleanValuePrinting {
        	
    	public static void main(String[] args) 
    	{
    		Boolean b = Boolean.FALSE;
    		
    		System.out.println("Checking Boolean.FALSE");
    		System.out.println(Boolean.FALSE);
    		
    		System.out.println("Checking Boolean.TRUE");
    		System.out.println(Boolean.TRUE);
    		
    		System.out.println("Checking b");
    		System.out.println(b);
    		
    		System.out.println("done");
    	}
    }

Regardless of order, the j2s version crashes when trying to print a Boolean.

**Comment by abego** [comment]
For the statement

    System.out.println(Boolean.FALSE);

Java2Script generates this JavaScript code

    System.out.println (Clazz.castObjectAs(Boolean.FALSE, "Object"));

I.e. it converts `FALSE` to a `Clazz.CastedObject` before passing it to `println`.

The current implementation of `System.out.println` uses `s + "\r\n"` to create the string to print: 

    System.out.println = function(s) {
        if (typeof s == "undefined") {
            s = "\r\n";
        } else if (s == null) {
            s = "null\r\n";
        } else {
            s = s + "\r\n";
        }
        C_$.cot(s);
    };

This fails because ` x + "..."` does not work for objects like `Clazz.CastedObject`.


Directly passing `Boolean.FALSE` to `System.out.println` (without `caseObjectAs`) would give the expected result.

However `System.out.println` should also be able to handle  `Clazz.CastedObject`  correctly, i.e. call `s.getObject().toString()` in those cases.

**Comment by BobHanson** [comment]
no longer an issue
